# Generated by Django 3.2.5 on 2021-11-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
