# Generated by Django 3.2.5 on 2021-11-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_file',
        ),
    ]
