# Generated by Django 3.2.5 on 2021-11-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_audio_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, default='Coldplay - Adventure Of A Lifetime.wav', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file_name',
            field=models.TextField(default='default'),
        ),
    ]
