# Generated by Django 3.2.5 on 2021-12-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211104_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDataStr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, default='dark.wav', null=True, upload_to=''),
        ),
    ]
