# Generated by Django 3.2.5 on 2021-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211208_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_name',
            field=models.TextField(default='example'),
        ),
        migrations.AlterField(
            model_name='audiodatastr',
            name='data',
            field=models.TextField(),
        ),
    ]
